# Generated by Django 3.2.9 on 2021-11-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_image_to_text_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_to_text',
            name='name',
        ),
    ]
